"""Grounded answer orchestration, provider selection, and output validation."""

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Protocol

from app.core.config import Settings
from app.cv_retrieval import (
    CvFinalRetrievalError,
    FinalCvRetrievalQuery,
    FinalCvRetrievalResult,
    FinalCvRetriever,
    build_final_cv_retriever,
)

from .client import GroundedAnswerProviderError
from .models import (
    GroundedAnswerDraft,
    GroundedAnswerProviderName,
    GroundedAnswerResponse,
    GroundedCandidateAnswer,
)
from .provider_selection import resolve_grounded_answer_provider
from .sources import (
    build_grounded_answer_sources,
    default_candidate_citation_ids,
    validate_grounded_answer_citations,
)


class GroundedAnswerProvider(Protocol):
    """Small provider contract used by orchestration and deterministic tests."""

    def generate(
        self,
        retrieval_result: FinalCvRetrievalResult,
        *,
        correction_feedback: Sequence[str] = (),
    ) -> GroundedAnswerDraft:
        """Generate one structured answer from the final retrieval package."""

        ...


@dataclass(frozen=True, slots=True)
class GroundedAnswerGenerationConfig:
    """Bounded correction and output-size policy for answer generation."""

    max_retries: int = 1
    max_answer_characters: int = 5000
    max_candidate_assessment_characters: int = 1800

    def __post_init__(self) -> None:
        if self.max_retries < 0:
            raise ValueError("Grounded answer retry count cannot be negative.")
        if self.max_answer_characters < 100:
            raise ValueError(
                "Grounded answer character limit must be at least 100."
            )
        if self.max_candidate_assessment_characters < 100:
            raise ValueError(
                "Candidate assessment character limit must be at least 100."
            )


@dataclass(frozen=True, slots=True)
class GroundedAnswerGenerationResult:
    """Accepted answer draft plus immutable retrieval and provider metadata."""

    retrieval_result: FinalCvRetrievalResult
    draft: GroundedAnswerDraft
    attempts: int
    provider_called: bool
    model_name: str
    provider_name: GroundedAnswerProviderName = "openai"

    def __post_init__(self) -> None:
        if self.attempts < 0:
            raise ValueError("Grounded answer attempts cannot be negative.")
        if self.provider_called != (self.attempts > 0):
            raise ValueError("Provider call state must match the attempt count.")
        if not self.model_name.strip():
            raise ValueError("Grounded answer model name is required.")

    @property
    def response(self) -> GroundedAnswerResponse:
        """Return the final API-ready response with cited source objects."""

        all_sources = build_grounded_answer_sources(self.retrieval_result)
        referenced_ids = _ordered_referenced_source_ids(self.draft)
        referenced_sources = [
            source for source in all_sources if source.source_id in referenced_ids
        ]
        warnings = list(self.draft.limitations)
        if self.provider_name == "deterministic" and self.draft.outcome != "unsupported":
            warnings.append(
                "Answer wording was generated by the deterministic no-key "
                "fallback rather than an external language model."
            )

        return GroundedAnswerResponse(
            outcome=self.draft.outcome,
            provider=self.provider_name,
            model=self.model_name,
            provider_called=self.provider_called,
            provider_attempts=self.attempts,
            answer=self.draft.answer,
            answer_citation_ids=self.draft.answer_citation_ids,
            candidates=self.draft.candidates,
            sources=referenced_sources,
            warnings=warnings,
        )


class GroundedAnswerGenerationFailed(RuntimeError):
    """Raised after a non-retryable error or exhausted correction budget."""

    def __init__(self, *, attempts: int, reasons: Sequence[str]) -> None:
        self.attempts = attempts
        self.reasons = tuple(reasons)
        super().__init__(
            f"Grounded answer generation failed after {attempts} attempt(s): "
            + "; ".join(self.reasons)
        )


class GroundedCvAnswerGenerator:
    """Retrieve evidence, generate wording, and validate the structured draft."""

    def __init__(
        self,
        config: GroundedAnswerGenerationConfig,
        *,
        retriever: FinalCvRetriever,
        provider: GroundedAnswerProvider | None,
        model_name: str,
        provider_name: GroundedAnswerProviderName = "openai",
    ) -> None:
        self._config = config
        self._retriever = retriever
        self._provider = provider
        self._model_name = model_name
        self._provider_name = provider_name

    def generate(
        self,
        query: FinalCvRetrievalQuery,
    ) -> GroundedAnswerGenerationResult:
        """Return deterministic or hosted-model wording over verified evidence."""

        try:
            retrieval_result = self._retriever.retrieve(query)
        except CvFinalRetrievalError as error:
            raise GroundedAnswerGenerationFailed(
                attempts=0,
                reasons=[str(error)],
            ) from error

        if retrieval_result.outcome == "unsupported":
            return self._deterministic_result(
                retrieval_result,
                _build_unsupported_draft(retrieval_result),
            )

        if self._provider is None:
            draft = _build_deterministic_draft(retrieval_result)
            problems = validate_grounded_answer_draft(
                draft,
                retrieval_result,
                config=self._config,
            )
            if problems:
                raise GroundedAnswerGenerationFailed(
                    attempts=0,
                    reasons=problems,
                )
            return self._deterministic_result(retrieval_result, draft)

        correction_feedback: tuple[str, ...] = ()
        total_attempts = self._config.max_retries + 1

        for attempt_number in range(1, total_attempts + 1):
            try:
                draft = self._provider.generate(
                    retrieval_result,
                    correction_feedback=correction_feedback,
                )
            except GroundedAnswerProviderError as error:
                if not error.retryable or attempt_number == total_attempts:
                    raise GroundedAnswerGenerationFailed(
                        attempts=attempt_number,
                        reasons=[str(error)],
                    ) from error
                correction_feedback = ()
                continue

            validation_problems = validate_grounded_answer_draft(
                draft,
                retrieval_result,
                config=self._config,
            )
            if not validation_problems:
                return GroundedAnswerGenerationResult(
                    retrieval_result=retrieval_result,
                    draft=draft,
                    attempts=attempt_number,
                    provider_called=True,
                    model_name=self._model_name,
                    provider_name=self._provider_name,
                )

            if attempt_number == total_attempts:
                raise GroundedAnswerGenerationFailed(
                    attempts=attempt_number,
                    reasons=validation_problems,
                )
            correction_feedback = tuple(validation_problems)

        raise RuntimeError("Grounded answer generation ended without a result.")

    def _deterministic_result(
        self,
        retrieval_result: FinalCvRetrievalResult,
        draft: GroundedAnswerDraft,
    ) -> GroundedAnswerGenerationResult:
        return GroundedAnswerGenerationResult(
            retrieval_result=retrieval_result,
            draft=draft,
            attempts=0,
            provider_called=False,
            model_name=(
                self._model_name
                if self._provider_name == "deterministic"
                else "deterministic-template-v1"
            ),
            provider_name="deterministic",
        )


def validate_grounded_answer_draft(
    draft: GroundedAnswerDraft,
    retrieval_result: FinalCvRetrievalResult,
    *,
    config: GroundedAnswerGenerationConfig,
) -> list[str]:
    """Validate model output against exact candidate and source contracts."""

    problems: list[str] = []

    if draft.outcome != retrieval_result.outcome:
        problems.append(
            "Draft outcome must equal the retrieval outcome "
            f"{retrieval_result.outcome!r}."
        )

    if len(draft.answer) > config.max_answer_characters:
        problems.append(
            "Overall answer exceeds the configured character limit of "
            f"{config.max_answer_characters}."
        )

    expected_ids = [
        candidate.candidate_id for candidate in retrieval_result.candidates
    ]
    actual_ids = [candidate.candidate_id for candidate in draft.candidates]
    if actual_ids != expected_ids:
        problems.append(
            "Draft candidates must exactly match retrieval order: "
            + ", ".join(expected_ids)
            + "."
        )

    if len(actual_ids) != len(set(actual_ids)):
        problems.append("Draft candidate IDs must be unique.")

    expected_by_id = {
        candidate.candidate_id: candidate
        for candidate in retrieval_result.candidates
    }
    for candidate_draft in draft.candidates:
        expected = expected_by_id.get(candidate_draft.candidate_id)
        if expected is None:
            continue
        _validate_candidate_draft(
            candidate_draft,
            expected,
            config=config,
            problems=problems,
        )

    if retrieval_result.outcome == "partial" and not draft.limitations:
        problems.append(
            "Partial answers must include at least one explicit limitation."
        )
    if retrieval_result.outcome == "supported" and not draft.candidates:
        problems.append("Supported answers must include retrieved candidates.")
    if retrieval_result.outcome == "unsupported":
        if draft.candidates:
            problems.append("Unsupported answers cannot include candidates.")
        if not draft.limitations:
            problems.append(
                "Unsupported answers must explain that evidence was not found."
            )

    problems.extend(
        validate_grounded_answer_citations(draft, retrieval_result)
    )
    return problems


def build_grounded_cv_answer_generator(
    settings: Settings,
) -> GroundedCvAnswerGenerator:
    """Build final retrieval plus the configured hosted or no-key provider."""

    resolved = resolve_grounded_answer_provider(settings)
    return GroundedCvAnswerGenerator(
        GroundedAnswerGenerationConfig(
            max_retries=settings.cv_grounded_answer_max_retries,
            max_answer_characters=(
                settings.cv_grounded_answer_max_answer_characters
            ),
            max_candidate_assessment_characters=(
                settings.cv_grounded_answer_max_candidate_assessment_characters
            ),
        ),
        retriever=build_final_cv_retriever(settings),
        provider=resolved.provider,
        model_name=resolved.model_name,
        provider_name=resolved.provider_name,
    )


def _validate_candidate_draft(
    candidate_draft: GroundedCandidateAnswer,
    expected,
    *,
    config: GroundedAnswerGenerationConfig,
    problems: list[str],
) -> None:
    """Check one candidate identity and requirement list without cross-mixing."""

    expected_name = expected.candidate_name or "Unknown candidate"
    expected_title = expected.professional_title or "Unknown title"
    expected_requirements = list(expected.matched_condition_labels)

    if candidate_draft.candidate_name != expected_name:
        problems.append(
            f"{expected.candidate_id} name must remain {expected_name!r}."
        )
    if candidate_draft.professional_title != expected_title:
        problems.append(
            f"{expected.candidate_id} title must remain {expected_title!r}."
        )
    if candidate_draft.matched_requirements != expected_requirements:
        problems.append(
            f"{expected.candidate_id} matched requirements must remain: "
            + ", ".join(expected_requirements)
            + "."
        )
    if (
        len(candidate_draft.assessment)
        > config.max_candidate_assessment_characters
    ):
        problems.append(
            f"{expected.candidate_id} assessment exceeds the configured "
            f"character limit of "
            f"{config.max_candidate_assessment_characters}."
        )


def _build_deterministic_draft(
    retrieval_result: FinalCvRetrievalResult,
) -> GroundedAnswerDraft:
    """Produce a useful no-key answer from deterministic WP6 contracts."""

    candidates: list[GroundedCandidateAnswer] = []
    answer_citations: list[str] = []
    for candidate in retrieval_result.candidates:
        citation_ids = list(default_candidate_citation_ids(candidate))
        answer_citations.extend(citation_ids)
        requirements = list(candidate.matched_condition_labels)
        support_label = (
            "Complete match"
            if candidate.support_level == "complete"
            else "Partial match"
        )
        candidates.append(
            GroundedCandidateAnswer(
                candidate_id=candidate.candidate_id,
                candidate_name=candidate.candidate_name or "Unknown candidate",
                professional_title=(
                    candidate.professional_title or "Unknown title"
                ),
                assessment=(
                    f"{support_label}: the indexed CV evidence supports "
                    + ", ".join(requirements)
                    + "."
                ),
                matched_requirements=requirements,
                citation_ids=citation_ids,
            )
        )

    names = ", ".join(candidate.candidate_name for candidate in candidates)
    if retrieval_result.outcome == "supported":
        subject = "a candidate" if len(candidates) == 1 else "candidates"
        answer = (
            f"The indexed CV evidence identifies {names} as {subject} with "
            "complete coverage of the supported requirements."
        )
        limitations: list[str] = []
    else:
        answer = (
            f"No candidate has complete coverage. The indexed evidence "
            f"identifies these high-confidence partial matches: {names}."
        )
        limitations = [retrieval_result.support_message]

    return GroundedAnswerDraft(
        outcome=retrieval_result.outcome,
        answer=answer,
        answer_citation_ids=list(dict.fromkeys(answer_citations)),
        candidates=candidates,
        limitations=limitations,
    )


def _build_unsupported_draft(
    retrieval_result: FinalCvRetrievalResult,
) -> GroundedAnswerDraft:
    """Return an honest no-evidence answer without making an LLM call."""

    return GroundedAnswerDraft(
        outcome="unsupported",
        answer=(
            "I could not identify any candidate with sufficiently supported "
            "evidence for this question in the indexed CV collection."
        ),
        answer_citation_ids=[],
        candidates=[],
        limitations=[retrieval_result.support_message],
    )


def _ordered_referenced_source_ids(
    draft: GroundedAnswerDraft,
) -> set[str]:
    """Return all source IDs referenced anywhere in the accepted draft."""

    ordered = list(draft.answer_citation_ids)
    for candidate in draft.candidates:
        ordered.extend(candidate.citation_ids)
    return set(ordered)
